### ISSUE TITLE
Failed to connect to downv6.qq.com

### ISSUE THREAD

**Issue by Ethan9877** [klxiaoniu/QQVersionList#58]
java.net.ConnectException: Failed to connect to downv6.qq.com/[::]:443
	at y2.l.e(SourceFile:139)
	at y2.l.c(SourceFile:160)
	at y2.e.a(SourceFile:735)
	at y2.a.a(SourceFile:58)
	at z2.f.b(SourceFile:124)
	at w2.b.a(SourceFile:137)
	at z2.f.b(SourceFile:124)
	at z2.a.a(SourceFile:605)
	at z2.f.b(SourceFile:124)
	at z2.a.a(SourceFile:148)
	at z2.f.b(SourceFile:124)
	at y2.i.g(SourceFile:97)
	at y2.i.e(SourceFile:44)
	at F1.f.run(SourceFile:21)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: java.net.ConnectException: Failed to connect to downv6.qq.com/0.0.0.0:443
		... 15 more
	Caused by: java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 443) from /127.0.0.1 (port 40380) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
		at libcore.io.IoBridge.isConnected(IoBridge.java:347)
		at libcore.io.IoBridge.connectErrno(IoBridge.java:237)
		at libcore.io.IoBridge.connect(IoBridge.java:179)
		at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
		at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:228)
		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
		at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
		at java.net.Socket.connect(Socket.java:646)
		at C2.n.e(SourceFile:6)
		at y2.l.e(SourceFile:74)
		... 14 more
	Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
		at libcore.io.IoBridge.isConnected(IoBridge.java:334)
		... 24 more
Caused by: java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 443) from /127.0.0.1 (port 40392) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
	at libcore.io.IoBridge.isConnected(IoBridge.java:347)
	at libcore.io.IoBridge.connectErrno(IoBridge.java:237)
	at libcore.io.IoBridge.connect(IoBridge.java:179)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:228)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:646)
	at C2.n.e(SourceFile:6)
	at y2.l.e(SourceFile:74)
	... 14 more
Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
	at libcore.io.IoBridge.isConnected(IoBridge.java:334)
	... 24 more
![Screenshot_2024-07-30-13-46-06-195_com xiaoniu qqversionlist](https://github.com/user-attachments/assets/7cafdf28-05d6-4e81-8e95-2b4a36818b83)

**Comment by klxiaoniu** [comment]
网络问题，你换个网络或者过会再试试
