### ISSUE TITLE
刷新后提示软件出错

### ISSUE THREAD

**Issue by yizhixianyuuuu** [klxiaoniu/QQVersionList#84]
**描述错误**
刷新后提示软件出错

**重现步骤**
重现行为的步骤：
1. 打开软件
2. 刷新
3. 看到错误

**期望行为**
修复问题

**截图**
![Screenshot_20241024_003758_com.xiaoniu.qqversionlist.jpg](https://github.com/user-attachments/assets/21d02564-19b0-4790-b89b-6797cf719703)

**QQ 版本列表实用工具（请填写以下信息）：**
- 版本：（例如 v1.4.0-Release）

**智能手机（请填写以下信息）：**
 - 设备：HUAWEI Mate 40 Pro
 - 操作系统：HarmonyOS 2.0 (Android 10)

**其他上下文**
android.content.res.Resources$NotFoundException: Resource ID #0x7f06019c
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:416)
	at android.content.res.Resources.getColor(Resources.java:1070)
	at android.content.Context.getColor(Context.java:671)
	at U1.I.n(SourceFile:293)
	at c2.a.m(SourceFile:9)
	at v2.E.run(SourceFile:115)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by ArcticFoxPro** [comment]
已经查明并完成此问题的修复，下版本（1.4.1）可以带上。

系统导航栏与底部应用导航栏在 Android Q 上发生重叠的问题一并修复。

**Comment by ArcticFoxPro** [comment]
https://github.com/klxiaoniu/QQVersionList/releases/tag/v1.4.1

QVT 1.4.1 已发布，请在此版本验证此问题是否被修复。

我先为您关闭这条 issue 了。若发现此问题仍未被修复，您可以随时打开此 issue。
